name: Generate profile metrics

on:
  schedule:
    - cron: "0 */12 * * *" # twice daily
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/metrics.yml'

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ama8ine1712
          template: classic
          base: header, repositories, activity, community, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_achievements: yes
          plugin_notable: yes

